// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// extractMolecules
DataFrame extractMolecules(std::string bam_fn, std::string tagname, std::int32_t max_dist);
RcppExport SEXP _speedranger_extractMolecules(SEXP bam_fnSEXP, SEXP tagnameSEXP, SEXP max_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bam_fn(bam_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type tagname(tagnameSEXP);
    Rcpp::traits::input_parameter< std::int32_t >::type max_dist(max_distSEXP);
    rcpp_result_gen = Rcpp::wrap(extractMolecules(bam_fn, tagname, max_dist));
    return rcpp_result_gen;
END_RCPP
}
// countBarcodes
StringVector countBarcodes(std::string inp_fn, std::string out_fn, std::string wl_fn);
RcppExport SEXP _speedranger_countBarcodes(SEXP inp_fnSEXP, SEXP out_fnSEXP, SEXP wl_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type inp_fn(inp_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_fn(out_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type wl_fn(wl_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(countBarcodes(inp_fn, out_fn, wl_fn));
    return rcpp_result_gen;
END_RCPP
}
// preprocessFastq
StringVector preprocessFastq(std::string cts_inp_fn, std::string fq1_inp_fn, std::string fq2_inp_fn, std::string fq1_out_fn, std::string fq2_out_fn);
RcppExport SEXP _speedranger_preprocessFastq(SEXP cts_inp_fnSEXP, SEXP fq1_inp_fnSEXP, SEXP fq2_inp_fnSEXP, SEXP fq1_out_fnSEXP, SEXP fq2_out_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type cts_inp_fn(cts_inp_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type fq1_inp_fn(fq1_inp_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type fq2_inp_fn(fq2_inp_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type fq1_out_fn(fq1_out_fnSEXP);
    Rcpp::traits::input_parameter< std::string >::type fq2_out_fn(fq2_out_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocessFastq(cts_inp_fn, fq1_inp_fn, fq2_inp_fn, fq1_out_fn, fq2_out_fn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_speedranger_extractMolecules", (DL_FUNC) &_speedranger_extractMolecules, 3},
    {"_speedranger_countBarcodes", (DL_FUNC) &_speedranger_countBarcodes, 3},
    {"_speedranger_preprocessFastq", (DL_FUNC) &_speedranger_preprocessFastq, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_speedranger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
