# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract putative DNA molecules from barcoded BAM file.
#'
#' @param bam_fn filename
#' @param tagname barcode tag name
#' @param max_dist maximum distance between reads in a molecule
#' @export
extractMolecules <- function(bam_fn, tagname = "BX", max_dist = 50e4L) {
    .Call('_speedranger_extractMolecules', PACKAGE = 'speedranger', bam_fn, tagname, max_dist)
}

#' Count barcodes
#'
#' @param inp_fn input FQ file
#' @param out_fn output counts file
#' @param wl_fn output counts file
#' @export
countBarcodes <- function(inp_fn, out_fn, wl_fn) {
    .Call('_speedranger_countBarcodes', PACKAGE = 'speedranger', inp_fn, out_fn, wl_fn)
}

#' Preprocess barcoded FASTQ files.
#'
#' @param cts_inp_fn input FQ file read 1
#' @param fq1_inp_fn input FQ file read 1
#' @param fq2_inp_fn input FQ file read 2
#' @param fq1_out_fn output FQ file read 1
#' @param fq2_out_fn output FQ file read 2
#' @export
preprocessFastq <- function(cts_inp_fn, fq1_inp_fn, fq2_inp_fn, fq1_out_fn, fq2_out_fn) {
    .Call('_speedranger_preprocessFastq', PACKAGE = 'speedranger', cts_inp_fn, fq1_inp_fn, fq2_inp_fn, fq1_out_fn, fq2_out_fn)
}

